name: Generate Artifact

on:
  workflow_dispatch:
    inputs:
      msg:
        type: string
        description: used to make filename
        rquired: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: make file
        shell: bash
        run:
          echo "<html><body>Hi</body></html" > ${{ inputs.msg }}.html

      - name: upload generated file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.msg }}
          path: ${{ inputs.msg }}.html
